variables:
  GITHUB_REPO_OWNER: emotiq
  GITHUB_REPO: sbcl-binaries
  VERSION: "1.4.7"
  PREFIX: "/usr/local"

# cache:
#   key: "${CI_PIPELINE_ID}"
#   paths:
#     - work/

stages:
  - build
  - test
  - release
  - deploy

build:macos:
  stage: build
  tags:
    - macos
  script:
    - ./sbcl-build.sh
  artifacts:
    expire_in: 1 week
    paths:
      - work/

build:linux:
  stage: build
  tags:
    - linux
  script:
    - ${CI_PROJECT_DIR}/sbcl-build.sh
  artifacts:
    expire_in: 1 week
    paths:
      - work/

test:macos:
  stage: test
  except:
    - tags
  tags:
    - macos
  script:
    - ./sbcl-test.sh
  dependencies:
    - build:macos

test:linux:
  stage: test
  except:
    - tags
  tags:
    - linux
  script:
    - ${CI_PROJECT_DIR}/sbcl-test.sh
  dependencies:
    - build:linux

release:
  stage: release
  tags:
    - linux
  only:
    - tags
  script:
    - ci/create-release.sh

.deploy: &deploy_definition
  stage: deploy
  script:
    - ./sbcl-deploy.sh
    - ci/upload-file.sh $(cat /tmp/artifact.txt)

deploy:linux:
  <<: *deploy_definition
  tags:
    - linux
  only:
    - tags
  dependencies:
    - build:linux

deploy:macos:
  <<: *deploy_definition
  tags:
    - macos
  only:
    - tags
  dependencies:
    - build:macos
