variables:
  GITHUB_USER: emotiq
  GITHUB_REPO: sbcl-binaries
  VERSION: "1.4.8"
  PREFIX: "/usr/local"

# cache:
#   key: "${CI_PIPELINE_ID}"
#   paths:
#     - work/

stages:
  - build
  - test
  - release
  - deploy

.build: &build_definition
  stage: build
  script:
    - ./sbcl-build.sh
  artifacts:
    expire_in: 1 week
    paths:
      - work/

.test: &test_definition
  stage: test
  script:
    - ./sbcl-test.sh

.deploy: &deploy_definition
  stage: deploy
  tags:
    - linux
  only:
    - tags
  script:
    - ./sbcl-deploy.sh
    - ci/upload-file.sh $(cat /tmp/artifact.txt)

build:macos:
  <<: *build_definition
  tags:
    - macos

build:linux:
  <<: *build_definition
  tags:
    - linux

test:macos:
  <<: *test_definition
  tags:
    - macos
  dependencies:
    - build:macos

test:linux:
  <<: *test_definition
  tags:
    - linux
  dependencies:
    - build:linux

release:
  stage: release
  tags:
    - linux
  only:
    - tags
  script:
    - github-release release --tag ${CI_COMMIT_TAG} -c ${CI_COMMIT_SHA} -d "${CI_COMMIT_MESSAGE}"

deploy:linux:
  <<: *deploy_definition
  dependencies:
    - build:linux
  variables:
    platform: linux

deploy:macos:
  <<: *deploy_definition
  dependencies:
    - build:macos
  variables:
    platform: darwin
