language: c
sudo: required
os:
  - linux

env:
  global:
    - VERSION=1.4.7
    - PREFIX=/usr/local

jobs:
  - stage: Build
    script: ./sbcl-build.sh
  - stage: Test
    script: ./sbcl-test.sh
  - stage: Deploy
    script:
      - ./sbcl-build.sh
      - ./sbcl-deploy.sh
    deploy:
      provider: releases
      api_key:
        secure: "ASqO1hpdEOzzeb9hk0abzsJIRxp7kwZ6ooBcd1N3xNGwxcl6p41rryhliir1XqH1APeiVsSbS1BBoSHlqglER+ESdkTvf2fQUmPI+bjtm1f5KRLnhO3BbS6dtq60KDmy3yms6Fu2BuuMTP4/dw0GWzbGOETGMGyJ+IAefAh2qLYa3mXnykVm2otNYRSfhVb5xgrkNCJw0lMXYnfciqnherLroYUShhrzF+KBKNgxdqHN7aRpkNWTl1PyETlvZgRjTTxD3hsATn1HhpqRrqRfj7d1t1wWyqWSrao3Jf+VHYBc/imHX2uagEILDG+5yWP+cs9SbR5jARvDrqgYY2ier8BxXWGumIj1DbNXOPB5tVMsJoV9QEpN2j+emDwYLjFic4YlgxPjgkKP8ty2o/s+/+Ppr+LittNXZWKXW3zRBfDubzJdoFjCJn5Qo6oQsQCJbbKz2CVxCE+7rn+sjag6h/qf9bPScjFtOACCQzbL1/IFOh109HO5fwaR1gX39/g5jmSP5ZV566Lvc06nhcz7dmPBtR17qQENguF8EnWutZvy7JZgHr8huOM+hm984kHVahv1o+d97AU3ZQXbBy5UliCkjCeP/aGskqVhfijZlqsc24drwHHi97o1LXSClPt6k7vnp2D44fjLQZJqItPcoF44KK1mhezym9yuUg3asOA="
      file: "$(cat /tmp/artifact.txt)"
      skip_cleanup: true
      on:
        tags: true
